# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crnn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='crnn.proto',
  package='crnn',
  syntax='proto3',
  serialized_options=_b('\n\025io.grpc.examples.crnnB\tCrnnProtoP\001\242\002\003HLW'),
  serialized_pb=_b('\n\ncrnn.proto\x12\x04\x63rnn\";\n\x0b\x43rnnRequest\x12\x0b\n\x03img\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x01(\t\x12\x10\n\x08\x62ox_list\x18\x03 \x01(\t\"\x1c\n\tCrnnReply\x12\x0f\n\x07message\x18\x01 \x01(\t2;\n\x07Greeter\x12\x30\n\x08idc_crnn\x12\x11.crnn.CrnnRequest\x1a\x0f.crnn.CrnnReply\"\x00\x42*\n\x15io.grpc.examples.crnnB\tCrnnProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_CRNNREQUEST = _descriptor.Descriptor(
  name='CrnnRequest',
  full_name='crnn.CrnnRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='crnn.CrnnRequest.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='crnn.CrnnRequest.shape', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='box_list', full_name='crnn.CrnnRequest.box_list', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=79,
)


_CRNNREPLY = _descriptor.Descriptor(
  name='CrnnReply',
  full_name='crnn.CrnnReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='crnn.CrnnReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=109,
)

DESCRIPTOR.message_types_by_name['CrnnRequest'] = _CRNNREQUEST
DESCRIPTOR.message_types_by_name['CrnnReply'] = _CRNNREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CrnnRequest = _reflection.GeneratedProtocolMessageType('CrnnRequest', (_message.Message,), dict(
  DESCRIPTOR = _CRNNREQUEST,
  __module__ = 'crnn_pb2'
  # @@protoc_insertion_point(class_scope:crnn.CrnnRequest)
  ))
_sym_db.RegisterMessage(CrnnRequest)

CrnnReply = _reflection.GeneratedProtocolMessageType('CrnnReply', (_message.Message,), dict(
  DESCRIPTOR = _CRNNREPLY,
  __module__ = 'crnn_pb2'
  # @@protoc_insertion_point(class_scope:crnn.CrnnReply)
  ))
_sym_db.RegisterMessage(CrnnReply)


DESCRIPTOR._options = None

_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='crnn.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=111,
  serialized_end=170,
  methods=[
  _descriptor.MethodDescriptor(
    name='idc_crnn',
    full_name='crnn.Greeter.idc_crnn',
    index=0,
    containing_service=None,
    input_type=_CRNNREQUEST,
    output_type=_CRNNREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
