# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import crnn_pb2 as crnn__pb2


class GreeterStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.idc_crnn = channel.unary_unary(
        '/crnn.Greeter/idc_crnn',
        request_serializer=crnn__pb2.CrnnRequest.SerializeToString,
        response_deserializer=crnn__pb2.CrnnReply.FromString,
        )


class GreeterServicer(object):
  """The greeting service definition.
  """

  def idc_crnn(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'idc_crnn': grpc.unary_unary_rpc_method_handler(
          servicer.idc_crnn,
          request_deserializer=crnn__pb2.CrnnRequest.FromString,
          response_serializer=crnn__pb2.CrnnReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'crnn.Greeter', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
