# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ctpn.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ctpn.proto',
  package='ModelRPC',
  syntax='proto3',
  serialized_pb=_b('\n\nctpn.proto\x12\x08ModelRPC\"*\n\x0crect_request\x12\x0b\n\x03img\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x01(\t\"\x1d\n\nrect_reply\x12\x0f\n\x07message\x18\x01 \x01(\t2B\n\x05Model\x12\x39\n\x07predict\x12\x16.ModelRPC.rect_request\x1a\x14.ModelRPC.rect_reply\"\x00\x42/\n\x19io.grpc.examples.modelrpcB\nModelProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_RECT_REQUEST = _descriptor.Descriptor(
  name='rect_request',
  full_name='ModelRPC.rect_request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='img', full_name='ModelRPC.rect_request.img', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shape', full_name='ModelRPC.rect_request.shape', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=66,
)


_RECT_REPLY = _descriptor.Descriptor(
  name='rect_reply',
  full_name='ModelRPC.rect_reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ModelRPC.rect_reply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=97,
)

DESCRIPTOR.message_types_by_name['rect_request'] = _RECT_REQUEST
DESCRIPTOR.message_types_by_name['rect_reply'] = _RECT_REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

rect_request = _reflection.GeneratedProtocolMessageType('rect_request', (_message.Message,), dict(
  DESCRIPTOR = _RECT_REQUEST,
  __module__ = 'ctpn_pb2'
  # @@protoc_insertion_point(class_scope:ModelRPC.rect_request)
  ))
_sym_db.RegisterMessage(rect_request)

rect_reply = _reflection.GeneratedProtocolMessageType('rect_reply', (_message.Message,), dict(
  DESCRIPTOR = _RECT_REPLY,
  __module__ = 'ctpn_pb2'
  # @@protoc_insertion_point(class_scope:ModelRPC.rect_reply)
  ))
_sym_db.RegisterMessage(rect_reply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\031io.grpc.examples.modelrpcB\nModelProtoP\001\242\002\003HLW'))

_MODEL = _descriptor.ServiceDescriptor(
  name='Model',
  full_name='ModelRPC.Model',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=99,
  serialized_end=165,
  methods=[
  _descriptor.MethodDescriptor(
    name='predict',
    full_name='ModelRPC.Model.predict',
    index=0,
    containing_service=None,
    input_type=_RECT_REQUEST,
    output_type=_RECT_REPLY,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MODEL)

DESCRIPTOR.services_by_name['Model'] = _MODEL

# @@protoc_insertion_point(module_scope)
