# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import ctpn_pb2 as ctpn__pb2


class ModelStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.predict = channel.unary_unary(
        '/ModelRPC.Model/predict',
        request_serializer=ctpn__pb2.rect_request.SerializeToString,
        response_deserializer=ctpn__pb2.rect_reply.FromString,
        )


class ModelServicer(object):
  """The greeting service definition.
  """

  def predict(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ModelServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'predict': grpc.unary_unary_rpc_method_handler(
          servicer.predict,
          request_deserializer=ctpn__pb2.rect_request.FromString,
          response_serializer=ctpn__pb2.rect_reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ModelRPC.Model', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
