# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import yolo_pb2 as yolo__pb2


class YOLOModelStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.predict = channel.unary_unary(
        '/YOLORPC.YOLOModel/predict',
        request_serializer=yolo__pb2.rect_request.SerializeToString,
        response_deserializer=yolo__pb2.rect_reply.FromString,
        )


class YOLOModelServicer(object):
  """The greeting service definition.
  """

  def predict(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_YOLOModelServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'predict': grpc.unary_unary_rpc_method_handler(
          servicer.predict,
          request_deserializer=yolo__pb2.rect_request.FromString,
          response_serializer=yolo__pb2.rect_reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'YOLORPC.YOLOModel', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
